# Configuración de Render.com para Docker
# Este archivo ayuda a Render.com a entender cómo desplegar la aplicación

services:
  - type: web
    name: writer-site
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # NO configurar buildCommand ni startCommand - el Dockerfile maneja todo
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: error
    # Puerto configurado en el Dockerfile
    healthCheckPath: /
