-- PostgreSQL Migration Script
-- Generated from SQLite database
-- Date: 2026-01-16 18:18:30

BEGIN;

-- Table: users
-- Records: 3

-- DELETE FROM users;

INSERT INTO users (id, name, email, email_verified_at, password, remember_token, created_at, updated_at, phone, address, city, postal_code, province, country) VALUES (1, 'Administrador', 'admin@example.com', NULL, '$2y$12$NAzHnuJ/0adfWy9T/phKxeCyZWMGrn7.UlZ7HwRMMB/79zzVENsY6', NULL, '2026-01-15 09:44:41', '2026-01-15 12:29:48', NULL, NULL, NULL, NULL, NULL, 'España') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, email_verified_at = EXCLUDED.email_verified_at, password = EXCLUDED.password, remember_token = EXCLUDED.remember_token, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, phone = EXCLUDED.phone, address = EXCLUDED.address, city = EXCLUDED.city, postal_code = EXCLUDED.postal_code, province = EXCLUDED.province, country = EXCLUDED.country;
INSERT INTO users (id, name, email, email_verified_at, password, remember_token, created_at, updated_at, phone, address, city, postal_code, province, country) VALUES (2, 'Kevin Perez', 'kevin@example.com', NULL, '$2y$12$I7yWsLpiwRx6PChLuiA9s.7KGKumM3N.DHIH7eaJbTbbHdX4unFTC', NULL, '2026-01-15 12:29:48', '2026-01-15 12:29:48', NULL, NULL, NULL, NULL, NULL, 'España') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, email_verified_at = EXCLUDED.email_verified_at, password = EXCLUDED.password, remember_token = EXCLUDED.remember_token, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, phone = EXCLUDED.phone, address = EXCLUDED.address, city = EXCLUDED.city, postal_code = EXCLUDED.postal_code, province = EXCLUDED.province, country = EXCLUDED.country;
INSERT INTO users (id, name, email, email_verified_at, password, remember_token, created_at, updated_at, phone, address, city, postal_code, province, country) VALUES (3, 'Test', 'test@test.es', NULL, '$2y$12$TwyVaFGIQK2T2xlWmquBVeazMLhMHlndsVIVzfkEjWFvfXO6E0PfC', 'itKzbALzGOZMXexO1Zc2l8j99BvREz3oyg2Tvqpk7HkUzbWLBffINPJcUwUC', '2026-01-16 10:48:18', '2026-01-16 10:48:18', '655444333', 'Calle test', 'Barcelona', '08254', 'Manresa', 'España') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, email_verified_at = EXCLUDED.email_verified_at, password = EXCLUDED.password, remember_token = EXCLUDED.remember_token, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, phone = EXCLUDED.phone, address = EXCLUDED.address, city = EXCLUDED.city, postal_code = EXCLUDED.postal_code, province = EXCLUDED.province, country = EXCLUDED.country;

-- Table: site_settings
-- Records: 1

-- DELETE FROM site_settings;

INSERT INTO site_settings (id, site_name, tagline, hero_text, hero_image, contact_email, created_at, updated_at, instagram_url, facebook_url, tiktok_url, privacy_policy, terms_of_service, legal_notice, cookie_policy, cookies_enabled, twitter_url, youtube_url, linkedin_url, pinterest_url) VALUES (1, 'Kevin Pérez Alarcón', NULL, 'Kevin Pérez Alarcón', 'hero/fXLf1D1G53nMSzoIyIdm8NRE1lg8DUcKAVUbFify.jpg', 'admin@example.com', '2026-01-15 09:44:41', '2026-01-16 16:53:40', 'https://instagram.com/tu-pagina', 'https://instagram.com/tu-pagina', 'https://instagram.com/tu-pagina', '<div>POLITICA DE PRIVACIDAD</div>', '<div>TERMINOS DE SERIVICO</div>', '<div>AVISO LEGAL</div>', '<div>POLITICA DE COOKIES</div>', TRUE, 'https://instagram.com/tu-pagina', 'https://instagram.com/tu-pagina', 'https://instagram.com/tu-pagina', NULL) ON CONFLICT (id) DO UPDATE SET site_name = EXCLUDED.site_name, tagline = EXCLUDED.tagline, hero_text = EXCLUDED.hero_text, hero_image = EXCLUDED.hero_image, contact_email = EXCLUDED.contact_email, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, instagram_url = EXCLUDED.instagram_url, facebook_url = EXCLUDED.facebook_url, tiktok_url = EXCLUDED.tiktok_url, privacy_policy = EXCLUDED.privacy_policy, terms_of_service = EXCLUDED.terms_of_service, legal_notice = EXCLUDED.legal_notice, cookie_policy = EXCLUDED.cookie_policy, cookies_enabled = EXCLUDED.cookies_enabled, twitter_url = EXCLUDED.twitter_url, youtube_url = EXCLUDED.youtube_url, linkedin_url = EXCLUDED.linkedin_url, pinterest_url = EXCLUDED.pinterest_url;

-- Table: pages
-- Records: 8

-- DELETE FROM pages;

INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (1, 'home', 'Inicio', NULL, '2026-01-15 09:44:41', '2026-01-15 09:44:41') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (2, 'about', 'Sobre mí', '<p>Me llamo <strong>Kevin Pérez Alarcón</strong>. Nací en Manresa el 27 de septiembre del 1991 y he crecido en el pueblo de Monistrol de Montserrat (Barcelona).</p><p>Cuando era pequeño comencé a tener interés por la escritura. Era un niño muy reservado y me costaba trasmitir lo que sentía con las personas de mi alrededor. Por ese motivo cuando estaba triste o algo me preocupaba me encerraba en mi habitación y escribía mis sentimientos y emociones en algunos cuadernos que guardaba en mi mesita de noche. Recuerdo que me gustaba inventarme historias para contárselas a mis amigos y cuando se las contaba ellos me expectantes por saber como iban a terminar.</p><p>En el año 2019 decidí escribir mi primera novela <em>Amor contra todo pronóstico</em> y pude cumplir el sueño de publicarla a través de una editorial de autoedición llamada Ediciones Ende. Un tiempo después decidí comenzar a estudiar unos cursos de escritura en una escuela llamada Atenèu Barcelonés situada en Barcelona.</p><p>Posteriormente de cursar el primer año me aventuré a escribir mi segunda novela <em>En la casa</em> que publiqué con la editorial también de autoedición Círculo Rojo con la que reedité mi anterior libro <em>Amor contra todo pronóstico</em>.</p><p>En aquel entonces yo trabajaba en un supermercado y un día fui de visita a un mercadillo que suelen hacer los domingos en una población que se llama Collbató y una señora me propuso que vendiera mis novelas en tal lugar. Pregunté al ayuntamiento y me dejaron promocionaras durante unas semanas. Me di cuenta de que había personas que se paraban y algunas me los compraban. Así que repetí más días allí y empecé a pedir sitio a otras localidades para también ponerme en los mercadillos.</p><p>Con el tiempo me percaté de que podría intentar vivir solo de mis libros y dejé mi trabajo en el supermercado para emprender un negocio vendiendo mis dos novelas en mercadillos, ferias, mercados municipales y en la vía pública. Consiguiendo sacar hasta 4 ediciones de <em>Amor contra todo pronóstico</em> y 5 de <em>En la casa</em>.</p><p>Con el tiempo me han llegado a comprar más de 5.000 libros en las calles. Cosa que estoy muy agradecido a cada una de las personas que me han ayudado a seguir soñando. Gracias a todos ellos puedo seguir viviendo de mis libros autoeditados.</p><p>Después de haber estudiado los 3 primeros cursos en la escuela de escritura publiqué mi tercera novela <em>Territorio Devastado</em> y poco más tarde mi cuarta <em>Vestido blanco de flores silvestres</em>. Ambas sacadas al mercado en 2025.</p>', '2026-01-15 09:44:41', '2026-01-15 13:02:48') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (3, 'contact', 'Contacto', '<p>Si quieres escribir, usa el formulario. Responderemos lo antes posible.</p>', '2026-01-15 09:44:41', '2026-01-15 09:44:41') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (4, 'faq', 'Preguntas frecuentes', '<h3>¿Cómo puedo comprar tus libros?</h3><p>Puedes comprar mis libros directamente desde esta web mediante tarjeta de crédito, PayPal o Bizum. También puedes encontrarme en mercadillos, ferias y mercados municipales.</p><h3>¿Qué incluye el precio?</h3><p>El precio incluye: libro + dedicatoria (opcional) + marcapáginas + envío certificado (con seguro) + embalaje.</p><h3>¿Haces envíos internacionales?</h3><p>Sí, realizo envíos a toda España. Para envíos internacionales, contacta conmigo directamente.</p><h3>¿Puedo conseguir una dedicatoria personalizada?</h3><p>Sí, puedes indicar en el pedido si deseas una dedicatoria personalizada y el texto que quieres que incluya.</p><h3>¿Dónde puedo encontrarte en persona?</h3><p>Me puedes encontrar en mercadillos, ferias y mercados municipales de diferentes localidades. Sigue mis redes sociales para conocer mis próximas apariciones.</p>', '2026-01-15 13:02:48', '2026-01-15 13:02:48') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (5, 'blog', 'Blog', '<p>Próximamente publicaré artículos sobre escritura, mis experiencias vendiendo libros en las calles, y reflexiones sobre el proceso creativo.</p>', '2026-01-15 13:02:48', '2026-01-15 13:02:48') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (6, 'photos-readers', 'Fotos con mis lectores en los mercados', '<p>Aquí compartiré fotos con mis lectores en los diferentes mercadillos y ferias donde me encuentro. ¡Gracias a todos por vuestro apoyo!</p>', '2026-01-15 13:02:48', '2026-01-15 13:02:48') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (7, 'photos-books', 'Fotos con mis novelas', '<p>Galería de imágenes de mis novelas en diferentes ubicaciones y eventos.</p>', '2026-01-15 13:02:48', '2026-01-15 13:02:48') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;
INSERT INTO pages (id, slug, title, content, created_at, updated_at) VALUES (8, 'offers', 'Ofertas y packs', '<p>Mantente atento a nuestras ofertas especiales durante Halloween, Black Friday, Navidad y Sant Jordi. Próximamente publicaremos packs especiales con descuentos.</p>', '2026-01-15 13:02:48', '2026-01-15 13:02:48') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, content = EXCLUDED.content, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at;

-- Table: books
-- Records: 9

-- DELETE FROM books;

INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (1, 'Cuaderno de sombra', 'Relatos cortos, densos, escritos para leerse despacio.', 'Una colección de textos breves que exploran el pulso entre luz y silencio. Edición cuidada, ritmo editorial, y una voz directa.', 18, NULL, NULL, TRUE, '2026-01-15 09:44:41', '2026-01-15 15:02:02', 7) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (2, 'La ciudad invisible', 'Una novela corta sobre lo que no se nombra.', 'Capítulos breves, escenas nítidas y un tono minimalista. Pensado para lectores que disfrutan de la pausa y la tensión contenida.', 22, NULL, NULL, TRUE, '2026-01-15 09:44:41', '2026-01-15 15:01:59', 8) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (3, 'Notas para el fin del día', 'Ensayo breve: escritura, oficio y mirada.', 'Un texto íntimo sobre el proceso creativo. Ideal para quien busca una lectura corta y profunda.', 14, NULL, NULL, FALSE, '2026-01-15 09:44:41', '2026-01-15 15:01:55', 9) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (4, 'El eco de las horas muertas', 'Una novela que explora la soledad urbana y los encuentros fortuitos que cambian el curso de una vida. Escrita con una prosa precisa y atmosférica.', '<p>En las calles de una ciudad que nunca duerme, un hombre busca respuestas en los espacios vacíos entre el ruido y el silencio. <em>El eco de las horas muertas</em> es una historia sobre la pérdida, la memoria y la posibilidad de encontrar luz en los lugares más oscuros.</p><p>Con un estilo narrativo que combina la precisión del minimalismo con la profundidad emocional, Kevin Perez construye un relato íntimo que habla directamente al corazón del lector. Cada capítulo es una pieza cuidadosamente tallada de un mosaico mayor, donde los personajes se cruzan en momentos que parecen casuales pero que están destinados a transformar sus vidas.</p><p>Una obra para leer en las noches tranquilas, cuando el mundo exterior se desvanece y solo queda el eco de las palabras en la mente.</p>', 24.99, NULL, NULL, TRUE, '2026-01-15 12:29:46', '2026-01-15 15:02:09', 5) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (5, 'Fragmentos de un invierno sin nombre', 'Una colección de relatos breves que capturan momentos de introspección y revelación. Cada historia es una ventana a un mundo interior complejo y fascinante.', '<p>En <em>Fragmentos de un invierno sin nombre</em>, Kevin Perez reúne doce relatos que exploran las múltiples capas de la experiencia humana. Desde encuentros casuales en cafeterías hasta reflexiones sobre el paso del tiempo, cada texto es una pequeña joya narrativa.</p><p>Los personajes de estos cuentos son personas comunes enfrentándose a momentos extraordinarios: una conversación que cambia todo, un recuerdo que resurge inesperadamente, una decisión que define un destino. Con una prosa elegante y precisa, Perez demuestra su dominio del relato corto, creando atmósferas densas y memorables en pocas páginas.</p><p>Ideal para lectores que buscan historias que los acompañen durante el día, que puedan leerse de una sentada pero que permanezcan en la memoria mucho después. Cada fragmento es una semilla que germina en la imaginación del lector.</p>', 19.5, NULL, NULL, TRUE, '2026-01-15 12:29:46', '2026-01-15 15:02:05', 6) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (6, 'Amor contra todo pronóstico', 'Un chico escribe un diario personal donde cuenta sus vivencias más importantes. Con el tiempo le ocurre algo que hace cambiar el rumbo de su vida y el de las personas que más quiere.', '<p>Un chico escribe un diario personal donde cuenta sus vivencias más importantes. Con el tiempo le ocurre algo que hace cambiar el rumbo de su vida y el de las personas que más quiere. Digamos que es algo totalmente imprevisible, muy difícil de digerir tanto para él como para la gente de su entorno más cercano.</p><p>Es probable que no hay más de diez personas en el mundo que les haya ocurrido lo mismo que a este chico y que estén identificadas mediáticamente. No es habitual contarlo, sino quedárselo para uno mismo por miedo al rechazo o lo que puedan pensar porque rompe con los estereotipos de la sociedad y es muy común sentirse juzgado por tanto es un asusto un tanto delicado ya que crea mucha controversia. Es un tema muy tabú y a las personas que les pasa se pueden sentir juzgadas e incomprendidas.</p><p><strong>Publicación:</strong> 2020<br><strong>Géneros:</strong> Romántico, drama, suspense, erótica, aventuras<br><strong>Páginas:</strong> 200<br><strong>Ediciones:</strong> 5<br><strong>Narrador:</strong> protagonista</p>', 18.95, 'covers/8ZImHPxyBmtpnvxIZN4LLswsRLOklVKgXpe83rJH.png', NULL, TRUE, '2026-01-15 13:02:48', '2026-01-15 15:01:36', 1) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (7, 'En la casa', 'La historia va de una chica que encuentra un trabajo de interna veinticuatro horas en una casa en el bosque. Debe cuidar de un señor mayor que tiene demencia.', '<p>La historia va de una chica que encuentra un trabajo de interna veinticuatro horas en una casa en el bosque. Debe cuidar de un señor mayor que tiene demencia. Sus labores son estar al tanto de él y también ocuparse de las tareas del hogar: limpiarle, cocinare…</p><p>A medida que pasan las horas y los días ella va viendo cosas un tanto extrañas en la casa rural y comienza a estar inquieta e insegura ya que es la primera vez que percibe algo así, aunque deberá hacerse fuerte e investigar si la morada guarda algún secreto y si hay personas del pasado que están involucradas con este misterio.</p><p><strong>Publicación:</strong> 2022<br><strong>Géneros:</strong> Novela negra, terror, misterio, suspense<br><strong>Páginas:</strong> 304<br><strong>Ediciones:</strong> 6<br><strong>Narrador:</strong> protagonista y omnisciente</p>', 22.95, 'covers/WvruPDTmHQShvWmd3VwLoSdSXc8kbfEI474V9dUD.png', NULL, TRUE, '2026-01-15 13:02:48', '2026-01-15 15:01:51', 2) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (8, 'Territorio Devastado', 'La novela cuenta como una familia de hace 400 años en el siglo XVI viven del campo. Un día por la noche alguien llama a la puerta del hogar de esta gente y ellos se despiertan, se asustan.', '<p>La novela cuenta como una familia de hace 400 años en el siglo XVI viven del campo, tienen un pequeño huertecito donde siembran verduras y viven del burro, la vaca y las gallinas que tiene en la planta baja de su humilde casita de barro.</p><p>Un día por la noche alguien llama a la puerta del hogar de esta gente y ellos se despiertan, se asustan. Bajan a ver de quién se trata temblorosos. Resulta ser un señor mayor que pide auxilio. Es el tabernero del pueblo, un señor mayor que es muy popular en el pueblo. Este está muy grave, tiene heridas por todo el cuerpo. La familia le preguntan qué le ha ocurrido preocupándose por él. Pero el señor no puede hablar y se desmaya.</p><p>Van a buscar al médico y cuando viene le da a la familia unas hierbas medicinales de aquella época. Al señor lo tienen en una cama durante unas horas intentando que se restablezca, sin embargo, de repente se escapa en esas condiciones tan desfavorables. ¿Cómo puede ser que alguien que se está muriendo en una cama se haya escapado así sin previo aviso?</p><p><strong>Publicación:</strong> 2025<br><strong>Géneros:</strong> Novela histórica, terror, ciencia ficción, misterio<br><strong>Páginas:</strong> 235<br><strong>Ediciones:</strong> 2<br><strong>Narrador:</strong> cámara</p>', 20.95, NULL, NULL, TRUE, '2026-01-15 13:02:48', '2026-01-15 15:02:17', 10) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO books (id, title, description, long_description, price, cover_image, stripe_price_id, active, created_at, updated_at, "order") VALUES (9, 'Vestido blanco de flores silvestres', 'A un joven que trabaja de tanatopractor se le avería el coche y debe ir en tren a la funeraria. Una vez estando ya en el interior ve como una preciosa chica de cabello largo y ojos almendrados sube en la siguiente parada.', '<p>A un joven que trabaja de tanatopractor se le avería el coche y debe ir en tren a la funeraria. Una vez estando ya en el interior ve como una preciosa chica de cabello largo y ojos almendrados sube en la siguiente parada y se sienta justo delante suyo, en el asiento libre que hay.</p><p>El chico se pone muy nervioso porque le ha encantado la mujer y se le ocurre escribirle unas notas en una libreta que guarda en la mochila. Le muestra las primeras dejándola algo desconcertada, pero cuando está apunto de entregarle la última donde había escrito su número de teléfono, la llaman por el móvil y se baja rápidamente a la siguiente estación quedándose él con las ganas de conocerla.</p><p>¿Volverá a coincidir con la misteriosa chica del tren? ¿Le convendrá hacerlo si se da la oportunidad o hay algo en ella que le pueda perjudicar?</p><p><strong>Publicación:</strong> 2025<br><strong>Géneros:</strong> novela negra, erótica, acción, misterio, drama, romántica y terror<br><strong>Páginas:</strong> 284<br><strong>Ediciones:</strong> 1<br><strong>Narrador:</strong> protagonista</p>', 22.95, 'covers/0B3KKu0Z0o5qvIWZYRkchpcEd2pyouv73LHs5Gt4.png', NULL, TRUE, '2026-01-15 13:02:48', '2026-01-15 15:02:14', 3) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, long_description = EXCLUDED.long_description, price = EXCLUDED.price, cover_image = EXCLUDED.cover_image, stripe_price_id = EXCLUDED.stripe_price_id, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";

-- Table: testimonials
-- Records: 5

-- DELETE FROM testimonials;

INSERT INTO testimonials (id, name, photo, review, rating, active, created_at, updated_at, "order") VALUES (1, 'María González', NULL, 'Los libros de Kevin Perez tienen una profundidad que te atrapa desde la primera página. Cada palabra está cuidadosamente elegida.', 5, TRUE, '2026-01-15 10:30:37', '2026-01-15 10:30:37', 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, photo = EXCLUDED.photo, review = EXCLUDED.review, rating = EXCLUDED.rating, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO testimonials (id, name, photo, review, rating, active, created_at, updated_at, "order") VALUES (2, 'Carlos Ruiz', NULL, 'Una narrativa única que combina elegancia y emoción. Recomiendo sus obras sin dudarlo.', 5, TRUE, '2026-01-15 10:30:37', '2026-01-15 10:30:37', 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, photo = EXCLUDED.photo, review = EXCLUDED.review, rating = EXCLUDED.rating, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO testimonials (id, name, photo, review, rating, active, created_at, updated_at, "order") VALUES (3, 'Ana Martínez', NULL, 'Kevin tiene el don de crear atmósferas que te transportan. Sus historias quedan contigo mucho después de leerlas.', 5, TRUE, '2026-01-15 10:30:37', '2026-01-15 10:30:37', 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, photo = EXCLUDED.photo, review = EXCLUDED.review, rating = EXCLUDED.rating, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO testimonials (id, name, photo, review, rating, active, created_at, updated_at, "order") VALUES (4, 'Sofia Ramírez', 'https://i.pravatar.cc/150?img=47', 'Leí "El eco de las horas muertas" en una sola noche. La prosa de Kevin Perez tiene algo hipnótico que te mantiene pegado a las páginas. Es raro encontrar un escritor que pueda crear tanta emoción con tan pocas palabras. Cada frase está perfectamente calibrada, cada silencio tiene significado. Definitivamente volveré a leer sus obras.', 5, TRUE, '2026-01-15 12:30:39', '2026-01-15 12:30:39', 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, photo = EXCLUDED.photo, review = EXCLUDED.review, rating = EXCLUDED.rating, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";
INSERT INTO testimonials (id, name, photo, review, rating, active, created_at, updated_at, "order") VALUES (5, 'Diego Morales', 'https://i.pravatar.cc/150?img=33', 'Los "Fragmentos de un invierno sin nombre" son pequeños milagros narrativos. Kevin tiene la capacidad de capturar momentos fugaces y convertirlos en historias universales. Su escritura es elegante sin ser pretenciosa, profunda sin ser oscura. Un autor que merece ser descubierto por más lectores.', 5, TRUE, '2026-01-15 12:30:39', '2026-01-15 12:30:39', 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, photo = EXCLUDED.photo, review = EXCLUDED.review, rating = EXCLUDED.rating, active = EXCLUDED.active, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at, "order" = EXCLUDED."order";


COMMIT;
